Repository SAGE-3/next, pull requests merged in 2023-09, with the labels that each got.

#703 [Snyk] Upgrade zod from 3.20.6 to 3.21.4
  webstack/package.json
  webstack/tools/schemas/package.json
  webstack/tools/schemas/yarn.lock
  webstack/yarn.lock
Labels: maintenance

#705 [Snyk] Upgrade three from 0.144.0 to 0.155.0
  webstack/libs/applications/src/lib/apps/GLTFViewer/GLTFViewer.tsx
  webstack/package.json
  webstack/yarn.lock
Labels: maintenance

#702 [Snyk] Upgrade zod-to-json-schema from 3.20.4 to 3.21.4
  webstack/tools/schemas/package.json
  webstack/tools/schemas/yarn.lock
Labels: maintenance

#712 [Snyk] Upgrade regenerator-runtime from 0.13.7 to 0.13.11
  webstack/apps/webapp/src/polyfills.ts
  webstack/package.json
  webstack/yarn.lock
Labels: maintenance, outdated

#704 [Snyk] Upgrade monaco-editor from 0.40.0 to 0.41.0
  webstack/package.json
  webstack/yarn.lock
Labels: maintenance, outdated

#728 Add grouped toolbar
  .github/workflows/client_linux.yaml
  webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx
  webstack/apps/webapp/src/app/pages/board/layers/ui/components/Panels/Kernels/KernelsPanel.tsx
  webstack/libs/applications/src/lib/apps.ts
  webstack/libs/applications/src/lib/apps/AIPane/AIPane.tsx
  webstack/libs/applications/src/lib/apps/BoardLink/BoardLink.tsx
  webstack/libs/applications/src/lib/apps/CSVViewer/CSVViewer.tsx
  webstack/libs/applications/src/lib/apps/ChartGenerator/ChartGenerator.tsx
  webstack/libs/applications/src/lib/apps/ChartMaker/ChartMaker.tsx
  webstack/libs/applications/src/lib/apps/Chat/Chat.tsx
  webstack/libs/applications/src/lib/apps/Clock/Clock.tsx
  webstack/libs/applications/src/lib/apps/Cobrowse/Cobrowse.tsx
  webstack/libs/applications/src/lib/apps/Counter/Counter.tsx
  webstack/libs/applications/src/lib/apps/DataTable/DataTable.tsx
  webstack/libs/applications/src/lib/apps/DeepZoomImage/DeepZoomImage.tsx
  webstack/libs/applications/src/lib/apps/EChartsViewer/EChartsViewer.tsx
  webstack/libs/applications/src/lib/apps/GLTFViewer/GLTFViewer.tsx
  webstack/libs/applications/src/lib/apps/HCDP/HCDP.tsx
  webstack/libs/applications/src/lib/apps/HCDP/data/hcdpStationData.tsx
  webstack/libs/applications/src/lib/apps/HCDP/viewers/MapViewer.tsx
  webstack/libs/applications/src/lib/apps/ImageViewer/ImageViewer.tsx
  webstack/libs/applications/src/lib/apps/JupyterLab/JupyterLab.tsx
  webstack/libs/applications/src/lib/apps/LeafLet/LeafLet.tsx
  webstack/libs/applications/src/lib/apps/Linker/Linker.tsx
  webstack/libs/applications/src/lib/apps/MapGL/MapGL.tsx
  webstack/libs/applications/src/lib/apps/Notepad/Notepad.tsx
  webstack/libs/applications/src/lib/apps/PDFResult/PDFResult.tsx
  webstack/libs/applications/src/lib/apps/PDFViewer/PDFViewer.tsx
  webstack/libs/applications/src/lib/apps/PluginApp/PluginApp.tsx
  webstack/libs/applications/src/lib/apps/RTCChat/RTCChat.tsx
  webstack/libs/applications/src/lib/apps/SageCell/SageCell.tsx
  webstack/libs/applications/src/lib/apps/SageCell/components/toolbar.tsx
  webstack/libs/applications/src/lib/apps/Screenshare/Screenshare.tsx
  webstack/libs/applications/src/lib/apps/Seer/Seer.tsx
  webstack/libs/applications/src/lib/apps/SensorOverview/SensorOverview.tsx
  webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
  webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx
  webstack/libs/applications/src/lib/apps/VegaLite/VegaLite.tsx
  webstack/libs/applications/src/lib/apps/VegaLiteViewer/VegaLiteViewer.tsx
  webstack/libs/applications/src/lib/apps/VideoViewer/VideoViewer.tsx
  webstack/libs/applications/src/lib/apps/VideoViewer/index.ts
  webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx
  webstack/libs/applications/src/lib/apps/Webview/Webview.tsx
  webstack/libs/applications/src/lib/schema.ts
  webstack/tools/generators/newapp/files/__name__.tsx__tmpl__
  webstack/tools/generators/newapp/index.ts
  webstack/tools/generators/regen/index.ts
  webstack/tools/schemas/yarn.lock
Labels: enhancement, frontend

#737 [Twilio] Upgrade packages. Use VP8 Codec Simulcast.
  webstack/libs/applications/src/lib/apps/TwilioScreenshare/TwilioScreenshare.tsx
  webstack/libs/backend/src/lib/utils/twilio.ts
  webstack/libs/frontend/src/lib/stores/twilio.ts
  webstack/package.json
  webstack/yarn.lock
Labels: enhancement

#739 [Annotations] Erase individual lines
  webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Line.tsx
  webstack/apps/webapp/src/app/pages/board/layers/background/components/Whiteboard/Whiteboard.tsx
Labels: enhancement, frontend
