Repository SAGE-3/next, pull requests merged in 2024-05, with the labels that each got.

#906 [Home Page] Board Search
  webstack/apps/webapp/src/app/pages/home/Home.tsx
Labels: enhancement, frontend

#913 [Stickies] OnInput
  webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
Labels: bug

#925 Improvements to Searching
  webstack/apps/webapp/src/app/pages/home/Home.tsx
  webstack/libs/shared/src/lib/utils/fuzzy-search.ts
  webstack/libs/shared/src/lib/utils/index.ts
Labels: enhancement

#931 Homepage Sidebar New Features and Improvements
  webstack/apps/webapp/src/app/pages/home/Home.tsx
  webstack/apps/webapp/src/app/pages/home/components/BoardSidebarRow.tsx
  webstack/apps/webapp/src/app/pages/home/components/index.ts
Labels: enhancement, frontend
