Repository SAGE-3/next, pull requests merged in 2025-03, with the labels that each got.

#1169 [PERFORMANCE] Fixed Drag Optimization Breaking
  webstack/libs/frontend/src/lib/providers/useCursorBoardPosition.tsx
Labels: bug

#1177 [Board] Setting the Default Board Position to the UiStore's State
  webstack/apps/webapp/src/app/pages/board/layers/background/BackgroundLayer.tsx
Labels: bug, frontend

#1182 [FIX] Intersection of App Toolbar and UI Navbar
  webstack/apps/webapp/src/app/pages/board/layers/ui/components/AppToolbar.tsx
Labels: bug

#1183 [FIX] Intersection of Grouped App Toolbar and UI Navbar
  webstack/apps/webapp/src/app/pages/board/layers/ui/components/LassoToolbar.tsx
Labels: bug, frontend

#1184 [UI Board] Back and Forward button to navigate quickly between boards
  webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx
  webstack/libs/frontend/src/lib/hooks/useRouteNav.tsx
Labels: enhancement, frontend
