Repository SAGE-3/next, pull requests merged in 2025-02, with the labels that each got.

#1134 [Python] Stickie update Yjs logic
  webstack/libs/applications/src/lib/apps/Stickie/Stickie.tsx
  webstack/libs/frontend/src/lib/providers/useYjs.tsx
Labels: bug

#1135 [APP] Fixed Embedded Links Recursive Refresh
  webstack/libs/applications/src/lib/apps/WebpageLink/WebpageLink.tsx
Labels: bug

#1151 [Twilio] Package Updates
  webstack/package.json
  webstack/yarn.lock
Labels: maintenance, outdated

#1157 [Twilio] Hotfix to remove video property to Twilio connect()
  webstack/libs/frontend/src/lib/stores/twilio.ts
Labels: bug

#1160 [Assets] Asset store now queries subscriptions and update
  webstack/apps/webapp/src/app/pages/board/layers/background/components/Background.tsx
  webstack/apps/webapp/src/app/pages/board/layers/ui/components/Menus/Menus/Asset/AssetsPanel.tsx
  webstack/apps/webapp/src/app/pages/home/Home.tsx
  webstack/libs/frontend/src/lib/hooks/useFiles.tsx
  webstack/libs/frontend/src/lib/stores/asset.ts
Labels: refactor, frontend

#1162 [Settings] User Settings Modal
  webstack/apps/webapp/src/app/pages/board/layers/ui/UILayer.tsx
  webstack/apps/webapp/src/app/pages/board/layers/ui/components/MainButton.tsx
  webstack/clients/electron/electron.js
  webstack/clients/electron/package.json
  webstack/clients/electron/preload.js
  webstack/libs/applications/src/lib/apps/Chat/Chat.tsx
  webstack/libs/frontend/src/lib/providers/useUserSettings.tsx
  webstack/libs/frontend/src/lib/ui/components/general/Clock.tsx
  webstack/libs/frontend/src/lib/ui/components/modals/Alfred.tsx
  webstack/libs/frontend/src/lib/ui/components/modals/EditUserSettingsModal.tsx
  webstack/libs/frontend/src/lib/ui/components/modals/EditVisibilityModal.tsx
  webstack/libs/frontend/src/lib/ui/components/modals/index.ts
Labels: enhancement, frontend

#1165 [TOOLS] New App Creation Fix
  webstack/tools/generators/newapp/index.ts
Labels: bug
